export interface HeaderProps {
  isLoggedIn: boolean;
  numItemsOfCart?: number;
}

export interface GenreProps {
  title: string;
  selected: boolean;
}

export interface GenreList {
  genreList: GenreProps[];
}

const createReadMeGenre = (
  title: string,
  selected: boolean = false,
): GenreProps => ({ title, selected });

export const ReadMeGenreList: GenreList = {
  genreList: [
    createReadMeGenre('건강취미'),
    createReadMeGenre('경제경영'),
    createReadMeGenre('고전'),
    createReadMeGenre('공무원 수험서'),
    createReadMeGenre('과학'),
    createReadMeGenre('대학교재/전문서적'),
    createReadMeGenre('만화'),
    createReadMeGenre('사회과학'),
    createReadMeGenre('수험서/자격증'),
    createReadMeGenre('소설/시/희곡', true),
    createReadMeGenre('어린이'),
    createReadMeGenre('에세이'),
    createReadMeGenre('여행', true),
    createReadMeGenre('역사'),
    createReadMeGenre('예술/대중문화'),
    createReadMeGenre('요리/살림'),
    createReadMeGenre('외국어'),
    createReadMeGenre('유아'),
    createReadMeGenre('인문학'),
    createReadMeGenre('자기계발'),
    createReadMeGenre('장르소설'),
    createReadMeGenre('잡지'),
    createReadMeGenre('전집'),
    createReadMeGenre('종교/역학'),
    createReadMeGenre('좋은 부모'),
    createReadMeGenre('청소년'),
    createReadMeGenre('컴퓨터/모바일'),
    createReadMeGenre('초등학교참고서'),
    createReadMeGenre('중학교참고서'),
    createReadMeGenre('고등학교참고서'),
  ],
};

export const communityCards = [
  {
    id: 1,
    profileImg: 'https://picsum.photos/id/10/200/300',
    userNickname: '리드미',
    createAt: '2024.01.31',
    bookCover: 'https://picsum.photos/id/11/200/300',
    bookTitle: '푸바오, 언제나 사랑해',
    review: '마음을 울리는 따뜻한 이야기.',
  },
  {
    id: 2,
    profileImg: 'https://picsum.photos/id/20/200/300',
    userNickname: '책읽는고양이',
    createAt: '2024.01.30',
    bookCover: 'https://picsum.photos/id/21/200/300',
    bookTitle: '별의 카르테',
    review: '밤하늘의 별처럼 반짝이는 이야기.',
  },
  {
    id: 3,
    profileImg: 'https://picsum.photos/id/30/200/300',
    userNickname: '페이지터너',
    createAt: '2024.01.29',
    bookCover: 'https://picsum.photos/id/31/200/300',
    bookTitle: '시간을 담은 집',
    review: '시간이 멈춘 듯한 마법의 순간들.',
  },
  {
    id: 4,
    profileImg: 'https://picsum.photos/id/40/200/300',
    userNickname: '서점나그네',
    createAt: '2024.01.28',
    bookCover: 'https://picsum.photos/id/41/200/300',
    bookTitle: '그림자의 노래',
    review: '그림자처럼 조용히 마음에 스며드는 이야기.',
  },
  {
    id: 5,
    profileImg: 'https://picsum.photos/id/50/200/300',
    userNickname: '도서관쥐',
    createAt: '2024.01.27',
    bookCover: 'https://picsum.photos/id/51/200/300',
    bookTitle: '해변의 카프카',
    review: '무거운 주제를 가볍게 풀어내는 마법.',
  },
  {
    id: 6,
    profileImg: 'https://picsum.photos/id/60/200/300',
    userNickname: '북웜',
    createAt: '2024.01.26',
    bookCover: 'https://picsum.photos/id/61/200/300',
    bookTitle: '우리들의 일그러진 영웅',
    review: '인간 내면의 깊이를 탐구하는 소설.',
  },
  {
    id: 7,
    profileImg: 'https://picsum.photos/id/70/200/300',
    userNickname: '문학소녀',
    createAt: '2024.01.25',
    bookCover: 'https://picsum.photos/id/71/200/300',
    bookTitle: '빛의 제국',
    review: '어둠 속에서도 빛을 찾아내는 이야기.',
  },
  {
    id: 8,
    profileImg: 'https://picsum.photos/id/80/200/300',
    userNickname: '책벌레',
    createAt: '2024.01.24',
    bookCover: 'https://picsum.photos/id/81/200/300',
    bookTitle: '종이 여자',
    review: '종이처럼 얇은 인생이 주는 깊은 울림.',
  },
  {
    id: 9,
    profileImg: 'https://picsum.photos/id/90/200/300',
    userNickname: '읽는토끼',
    createAt: '2024.01.23',
    bookCover: 'https://picsum.photos/id/91/200/300',
    bookTitle: '꿈의 해석',
    review: '꿈을 통해 자신을 이해하는 여정.',
  },
  {
    id: 10,
    profileImg: 'https://picsum.photos/id/100/200/300',
    userNickname: '노을사랑',
    createAt: '2024.01.22',
    bookCover: 'https://picsum.photos/id/101/200/300',
    bookTitle: '마법의 섬',
    review: '상상력을 자극하는 판타지 여행.',
  },
  {
    id: 11,
    profileImg: 'https://picsum.photos/id/110/200/300',
    userNickname: '별바라기',
    createAt: '2024.01.21',
    bookCover: 'https://picsum.photos/id/111/200/300',
    bookTitle: '숲속의 비밀',
    review: '자연과 하나되는 신비로운 경험.',
  },
  {
    id: 12,
    profileImg: 'https://picsum.photos/id/120/200/300',
    userNickname: '바람돌이',
    createAt: '2024.01.20',
    bookCover: 'https://picsum.photos/id/121/200/300',
    bookTitle: '시간 여행자',
    review: '시간을 넘나드는 아슬아슬한 모험.',
  },
  {
    id: 13,
    profileImg: 'https://picsum.photos/id/130/200/300',
    userNickname: '하늘소리',
    createAt: '2024.01.19',
    bookCover: 'https://picsum.photos/id/131/200/300',
    bookTitle: '감정의 색',
    review: '감정이 색으로 표현될 때 생기는 이야기.',
  },
  {
    id: 14,
    profileImg: 'https://picsum.photos/id/140/200/300',
    userNickname: '물결무늬',
    createAt: '2024.01.18',
    bookCover: 'https://picsum.photos/id/141/200/300',
    bookTitle: '거울 속으로',
    review: '거울이 우리에게 보여주는 또 다른 세계.',
  },
  {
    id: 15,
    profileImg: 'https://picsum.photos/id/150/200/300',
    userNickname: '모래알',
    createAt: '2024.01.17',
    bookCover: 'https://picsum.photos/id/151/200/300',
    bookTitle: '시간의 모래',
    review: '모래알처럼 흘러가는 시간 속 사랑 이야기.',
  },
  {
    id: 16,
    profileImg: 'https://picsum.photos/id/160/200/300',
    userNickname: '별빛조각',
    createAt: '2024.01.16',
    bookCover: 'https://picsum.photos/id/161/200/300',
    bookTitle: '우주의 끝',
    review: '무한한 우주를 여행하며 찾은 소중한 진실.',
  },
  {
    id: 17,
    profileImg: 'https://picsum.photos/id/170/200/300',
    userNickname: '파도소리',
    createAt: '2024.01.15',
    bookCover: 'https://picsum.photos/id/171/200/300',
    bookTitle: '바다의 속삭임',
    review: '바다가 들려주는 잔잔한 이야기들.',
  },
  {
    id: 18,
    profileImg: 'https://picsum.photos/id/180/200/300',
    userNickname: '책갈피',
    createAt: '2024.01.14',
    bookCover: 'https://picsum.photos/id/181/200/300',
    bookTitle: '잃어버린 시간을 찾아서',
    review: '잊혀진 시간 속에서 찾은 소중한 기억.',
  },
  {
    id: 19,
    profileImg: 'https://picsum.photos/id/190/200/300',
    userNickname: '꿈꾸는자',
    createAt: '2024.01.13',
    bookCover: 'https://picsum.photos/id/191/200/300',
    bookTitle: '꿈의 집',
    review: '꿈과 현실이 교차하는 신비로운 경험.',
  },
  {
    id: 20,
    profileImg: 'https://picsum.photos/id/200/200/300',
    userNickname: '빛나는밤',
    createAt: '2024.01.12',
    bookCover: 'https://picsum.photos/id/201/200/300',
    bookTitle: '별이 빛나는 밤에',
    review: '별빛 아래에서 펼쳐지는 감성적인 이야기.',
  },
];

